name: Build Binaries for BirdNET-Go release

on:
  release:
    types: [created, edited]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build and attach to Release
      uses: tphakala/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.22.1.linux-amd64.tar.gz"
        md5sum: false
        sha256sum: false
        compress_assets: auto
        build_command: make ${{ matrix.goos }}_${{ matrix.goarch }}
        extra_files: libtensorflowlite_c.so

  docker-tagging:
    runs-on: ubuntu-20.04
    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Generate downcase repository name'
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    - name: Tag docker image with release version
      run: |
        docker pull ghcr.io/${{ env.REPO }}:${{ github.sha }}
        docker tag ghcr.io/${{ env.REPO }}:${{ github.sha }} ghcr.io/${{ env.REPO }}:${{ github.event.release.tag_name }}
        docker tag ghcr.io/${{ env.REPO }}:${{ github.sha }} ghcr.io/${{ env.REPO }}:latest

    - name: Push tagged docker images
      run: |
        docker push ghcr.io/${{ env.REPO }}:${{ github.event.release.tag_name }}
        docker push ghcr.io/${{ env.REPO }}:latest
